//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calmedic.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayFormatResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayFormatResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calmedic.Resources.Shared.DisplayFormatResource", typeof(DisplayFormatResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dni.
        /// </summary>
        public static string Days_Few {
            get {
                return ResourceManager.GetString("Days_Few", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dni.
        /// </summary>
        public static string Days_Many {
            get {
                return ResourceManager.GetString("Days_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dzień.
        /// </summary>
        public static string Days_One {
            get {
                return ResourceManager.GetString("Days_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to godziny.
        /// </summary>
        public static string Hours_Few {
            get {
                return ResourceManager.GetString("Hours_Few", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to godzin.
        /// </summary>
        public static string Hours_Many {
            get {
                return ResourceManager.GetString("Hours_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to godzinę.
        /// </summary>
        public static string Hours_One {
            get {
                return ResourceManager.GetString("Hours_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minuty.
        /// </summary>
        public static string Minutes_Few {
            get {
                return ResourceManager.GetString("Minutes_Few", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minut.
        /// </summary>
        public static string Minutes_Many {
            get {
                return ResourceManager.GetString("Minutes_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutę.
        /// </summary>
        public static string Minutes_One {
            get {
                return ResourceManager.GetString("Minutes_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miesiące.
        /// </summary>
        public static string Months_Few {
            get {
                return ResourceManager.GetString("Months_Few", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miesięcy.
        /// </summary>
        public static string Months_Many {
            get {
                return ResourceManager.GetString("Months_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miesiąc.
        /// </summary>
        public static string Months_One {
            get {
                return ResourceManager.GetString("Months_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lata.
        /// </summary>
        public static string Years_Few {
            get {
                return ResourceManager.GetString("Years_Few", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lat.
        /// </summary>
        public static string Years_Many {
            get {
                return ResourceManager.GetString("Years_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rok.
        /// </summary>
        public static string Years_One {
            get {
                return ResourceManager.GetString("Years_One", resourceCulture);
            }
        }
    }
}
