//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calmedic.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calmedic.Resources.Shared.ErrorResource", typeof(ErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak dostępu.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto jest niaktywne.
        /// </summary>
        public static string AccountInactive {
            get {
                return ResourceManager.GetString("AccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje konto zostało utworzone, kliknij na poniższy link żeby utworzyć hasło: &lt;br /&gt; &lt;a href=&apos;{0}&apos;&gt;Utwórz hasło&lt;/a&gt;.
        /// </summary>
        public static string ConfirmationMessageContent {
            get {
                return ResourceManager.GetString("ConfirmationMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzenie konta.
        /// </summary>
        public static string ConfirmationMessageSubject {
            get {
                return ResourceManager.GetString("ConfirmationMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można edytować roli Adminsitrator.
        /// </summary>
        public static string EditRoleAdmin {
            get {
                return ResourceManager.GetString("EditRoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepotwierdzono adresu email.
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups! Coś poszło nie tak!.
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W celu zmiany hasła, kliknij na poniższy link: &lt;br /&gt; &lt;a href=&apos;{0}&apos;&gt;Zmień hasło&lt;/a&gt;.
        /// </summary>
        public static string ForgotPasswordContent {
            get {
                return ResourceManager.GetString("ForgotPasswordContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana hasła.
        /// </summary>
        public static string ForgotPasswordSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailMessageSending id: {0}.
        /// </summary>
        public static string MailMessageSending {
            get {
                return ResourceManager.GetString("MailMessageSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik nie może być większy niż {0} MB.
        /// </summary>
        public static string MaxFileLarge {
            get {
                return ResourceManager.GetString("MaxFileLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowe wartośći w modelu.
        /// </summary>
        public static string ModelIsNotValid {
            get {
                return ResourceManager.GetString("ModelIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak danych.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login nie został dodany.
        /// </summary>
        public static string NoLoginAdded {
            get {
                return ResourceManager.GetString("NoLoginAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak ustawienia.
        /// </summary>
        public static string NoSetting {
            get {
                return ResourceManager.GetString("NoSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak ustawień.
        /// </summary>
        public static string NoSettings {
            get {
                return ResourceManager.GetString("NoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość musi być między {1} i {2}.
        /// </summary>
        public static string RangeErrorBetween {
            get {
                return ResourceManager.GetString("RangeErrorBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość musi być nie większa niż {2}.
        /// </summary>
        public static string RangeErrorMaxOnly {
            get {
                return ResourceManager.GetString("RangeErrorMaxOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość musi być nie mniejsza niż {1}.
        /// </summary>
        public static string RangeErrorMinOnly {
            get {
                return ResourceManager.GetString("RangeErrorMinOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole jest wymagane.
        /// </summary>
        public static string RequiredShort {
            get {
                return ResourceManager.GetString("RequiredShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rola nie została znaleziona.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole nie może przekraczać {2} znaków długości.
        /// </summary>
        public static string StringLengthMax {
            get {
                return ResourceManager.GetString("StringLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekst przekracza dozwoloną ilość znaków.
        /// </summary>
        public static string StringTooLong {
            get {
                return ResourceManager.GetString("StringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol nie jest unikalny.
        /// </summary>
        public static string SymbolNotUnique {
            get {
                return ResourceManager.GetString("SymbolNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd składni.
        /// </summary>
        public static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik jest już dodany do wybranej roli.
        /// </summary>
        public static string UserAddedToRole {
            get {
                return ResourceManager.GetString("UserAddedToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik został już dodany.
        /// </summary>
        public static string UserAlreadyAdded {
            get {
                return ResourceManager.GetString("UserAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono użytkwonika.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne dane.
        /// </summary>
        public static string WrongData {
            get {
                return ResourceManager.GetString("WrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny adres email.
        /// </summary>
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędny typ pliku.
        /// </summary>
        public static string WrongFileType {
            get {
                return ResourceManager.GetString("WrongFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne dane logowania.
        /// </summary>
        public static string WrongLoginData {
            get {
                return ResourceManager.GetString("WrongLoginData", resourceCulture);
            }
        }
    }
}
